use super::control::consts::Get;

CONST!(MAX_TEXTURE_IMAGE_UNITS, i32);
CONST!(MAX_COMBINED_TEXTURE_IMAGE_UNITS, i32);
CONST!(MAX_TEXTURE_BUFFER_SIZE, i32);
CONST!(MAX_TEXTURE_SIZE, i32);
CONST!(MAX_UNIFORM_BUFFER_BINDINGS, i32);
CONST!(MAX_SHADER_STORAGE_BUFFER_BINDINGS, i32);
CONST!(MAX_UNIFORM_BLOCK_SIZE, i32);
CONST!(MAX_SHADER_STORAGE_BLOCK_SIZE, i32);
