#[rustfmt::skip]
pub mod s {
pub trait TupleSwizzle2<A: Copy, B: Copy>: Sized {
	fn s(self) -> (A, B);
	#[inline(always)] fn x(self) -> A { self.s().0 }
	#[inline(always)] fn y(self) -> B { self.s().1 }
	#[inline(always)] fn xx(self) -> (A, A) { let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn xy(self) -> (A, B) { let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn yx(self) -> (B, A) { let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn yy(self) -> (B, B) { let s = self.s(); (s.1, s.1) }

	#[inline(always)] fn r(self) -> A { self.s().0 }
	#[inline(always)] fn g(self) -> B { self.s().1 }
	#[inline(always)] fn rr(self) -> (A, A) { let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn rg(self) -> (A, B) { let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn gr(self) -> (B, A) { let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn gg(self) -> (B, B) { let s = self.s(); (s.1, s.1) }
}
pub trait TupleSwizzle3<A: Copy, B: Copy, C: Copy>: Sized {
	fn s(self) -> (A, B, C);
	#[inline(always)] fn x(self) -> A { self.s().0 }
	#[inline(always)] fn y(self) -> B { self.s().1 }
	#[inline(always)] fn z(self) -> C { self.s().2 }
	#[inline(always)] fn xx(self) -> (A, A){ let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn xy(self) -> (A, B){ let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn xz(self) -> (A, C){ let s = self.s(); (s.0, s.2) }
	#[inline(always)] fn yx(self) -> (B, A){ let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn yy(self) -> (B, B){ let s = self.s(); (s.1, s.1) }
	#[inline(always)] fn yz(self) -> (B, C){ let s = self.s(); (s.1, s.2) }
	#[inline(always)] fn zx(self) -> (C, A){ let s = self.s(); (s.2, s.0) }
	#[inline(always)] fn zy(self) -> (C, B){ let s = self.s(); (s.2, s.1) }
	#[inline(always)] fn zz(self) -> (C, C){ let s = self.s(); (s.2, s.2) }
	#[inline(always)] fn xxx(self) -> (A, A, A) { let s = self.s(); (s.0, s.0, s.0) }
	#[inline(always)] fn xxy(self) -> (A, A, B) { let s = self.s(); (s.0, s.0, s.1) }
	#[inline(always)] fn xxz(self) -> (A, A, C) { let s = self.s(); (s.0, s.0, s.2) }
	#[inline(always)] fn xyx(self) -> (A, B, A) { let s = self.s(); (s.0, s.1, s.0) }
	#[inline(always)] fn xyy(self) -> (A, B, B) { let s = self.s(); (s.0, s.1, s.1) }
	#[inline(always)] fn xyz(self) -> (A, B, C) { let s = self.s(); (s.0, s.1, s.2) }
	#[inline(always)] fn xzx(self) -> (A, C, A) { let s = self.s(); (s.0, s.2, s.0) }
	#[inline(always)] fn xzy(self) -> (A, C, B) { let s = self.s(); (s.0, s.2, s.1) }
	#[inline(always)] fn xzz(self) -> (A, C, C) { let s = self.s(); (s.0, s.2, s.2) }
	#[inline(always)] fn yxx(self) -> (B, A, A) { let s = self.s(); (s.1, s.0, s.0) }
	#[inline(always)] fn yxy(self) -> (B, A, B) { let s = self.s(); (s.1, s.0, s.1) }
	#[inline(always)] fn yxz(self) -> (B, A, C) { let s = self.s(); (s.1, s.0, s.2) }
	#[inline(always)] fn yyx(self) -> (B, B, A) { let s = self.s(); (s.1, s.1, s.0) }
	#[inline(always)] fn yyy(self) -> (B, B, B) { let s = self.s(); (s.1, s.1, s.1) }
	#[inline(always)] fn yyz(self) -> (B, B, C) { let s = self.s(); (s.1, s.1, s.2) }
	#[inline(always)] fn yzx(self) -> (B, C, A) { let s = self.s(); (s.1, s.2, s.0) }
	#[inline(always)] fn yzy(self) -> (B, C, B) { let s = self.s(); (s.1, s.2, s.1) }
	#[inline(always)] fn yzz(self) -> (B, C, C) { let s = self.s(); (s.1, s.2, s.2) }
	#[inline(always)] fn zxx(self) -> (C, A, A) { let s = self.s(); (s.2, s.0, s.0) }
	#[inline(always)] fn zxy(self) -> (C, A, B) { let s = self.s(); (s.2, s.0, s.1) }
	#[inline(always)] fn zxz(self) -> (C, A, C) { let s = self.s(); (s.2, s.0, s.2) }
	#[inline(always)] fn zyx(self) -> (C, B, A) { let s = self.s(); (s.2, s.1, s.0) }
	#[inline(always)] fn zyy(self) -> (C, B, B) { let s = self.s(); (s.2, s.1, s.1) }
	#[inline(always)] fn zyz(self) -> (C, B, C) { let s = self.s(); (s.2, s.1, s.2) }
	#[inline(always)] fn zzx(self) -> (C, C, A) { let s = self.s(); (s.2, s.2, s.0) }
	#[inline(always)] fn zzy(self) -> (C, C, B) { let s = self.s(); (s.2, s.2, s.1) }
	#[inline(always)] fn zzz(self) -> (C, C, C) { let s = self.s(); (s.2, s.2, s.2) }

	#[inline(always)] fn r(self) -> A { self.s().0 }
	#[inline(always)] fn g(self) -> B { self.s().1 }
	#[inline(always)] fn b(self) -> C { self.s().2 }
	#[inline(always)] fn rr(self) -> (A, A){ let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn rg(self) -> (A, B){ let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn rb(self) -> (A, C){ let s = self.s(); (s.0, s.2) }
	#[inline(always)] fn gr(self) -> (B, A){ let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn gg(self) -> (B, B){ let s = self.s(); (s.1, s.1) }
	#[inline(always)] fn gb(self) -> (B, C){ let s = self.s(); (s.1, s.2) }
	#[inline(always)] fn br(self) -> (C, A){ let s = self.s(); (s.2, s.0) }
	#[inline(always)] fn bg(self) -> (C, B){ let s = self.s(); (s.2, s.1) }
	#[inline(always)] fn bb(self) -> (C, C){ let s = self.s(); (s.2, s.2) }
	#[inline(always)] fn rrr(self) -> (A, A, A) { let s = self.s(); (s.0, s.0, s.0) }
	#[inline(always)] fn rrg(self) -> (A, A, B) { let s = self.s(); (s.0, s.0, s.1) }
	#[inline(always)] fn rrb(self) -> (A, A, C) { let s = self.s(); (s.0, s.0, s.2) }
	#[inline(always)] fn rgr(self) -> (A, B, A) { let s = self.s(); (s.0, s.1, s.0) }
	#[inline(always)] fn rgg(self) -> (A, B, B) { let s = self.s(); (s.0, s.1, s.1) }
	#[inline(always)] fn rgb(self) -> (A, B, C) { let s = self.s(); (s.0, s.1, s.2) }
	#[inline(always)] fn rbr(self) -> (A, C, A) { let s = self.s(); (s.0, s.2, s.0) }
	#[inline(always)] fn rbg(self) -> (A, C, B) { let s = self.s(); (s.0, s.2, s.1) }
	#[inline(always)] fn rbb(self) -> (A, C, C) { let s = self.s(); (s.0, s.2, s.2) }
	#[inline(always)] fn grr(self) -> (B, A, A) { let s = self.s(); (s.1, s.0, s.0) }
	#[inline(always)] fn grg(self) -> (B, A, B) { let s = self.s(); (s.1, s.0, s.1) }
	#[inline(always)] fn grb(self) -> (B, A, C) { let s = self.s(); (s.1, s.0, s.2) }
	#[inline(always)] fn ggr(self) -> (B, B, A) { let s = self.s(); (s.1, s.1, s.0) }
	#[inline(always)] fn ggg(self) -> (B, B, B) { let s = self.s(); (s.1, s.1, s.1) }
	#[inline(always)] fn ggb(self) -> (B, B, C) { let s = self.s(); (s.1, s.1, s.2) }
	#[inline(always)] fn gbr(self) -> (B, C, A) { let s = self.s(); (s.1, s.2, s.0) }
	#[inline(always)] fn gbg(self) -> (B, C, B) { let s = self.s(); (s.1, s.2, s.1) }
	#[inline(always)] fn gbb(self) -> (B, C, C) { let s = self.s(); (s.1, s.2, s.2) }
	#[inline(always)] fn brr(self) -> (C, A, A) { let s = self.s(); (s.2, s.0, s.0) }
	#[inline(always)] fn brg(self) -> (C, A, B) { let s = self.s(); (s.2, s.0, s.1) }
	#[inline(always)] fn brb(self) -> (C, A, C) { let s = self.s(); (s.2, s.0, s.2) }
	#[inline(always)] fn bgr(self) -> (C, B, A) { let s = self.s(); (s.2, s.1, s.0) }
	#[inline(always)] fn bgg(self) -> (C, B, B) { let s = self.s(); (s.2, s.1, s.1) }
	#[inline(always)] fn bgb(self) -> (C, B, C) { let s = self.s(); (s.2, s.1, s.2) }
	#[inline(always)] fn bbr(self) -> (C, C, A) { let s = self.s(); (s.2, s.2, s.0) }
	#[inline(always)] fn bbg(self) -> (C, C, B) { let s = self.s(); (s.2, s.2, s.1) }
	#[inline(always)] fn bbb(self) -> (C, C, C) { let s = self.s(); (s.2, s.2, s.2) }
}
pub trait TupleSwizzle4<A: Copy, B: Copy, C: Copy, D: Copy>: Sized {
	fn s(self) -> (A, B, C, D);
	#[inline(always)] fn x(self) -> A { self.s().0 }
	#[inline(always)] fn y(self) -> B { self.s().1 }
	#[inline(always)] fn z(self) -> C { self.s().2 }
	#[inline(always)] fn w(self) -> D { self.s().3 }
	#[inline(always)] fn xx(self) -> (A, A) { let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn xy(self) -> (A, B) { let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn xz(self) -> (A, C) { let s = self.s(); (s.0, s.2) }
	#[inline(always)] fn xw(self) -> (A, D) { let s = self.s(); (s.0, s.3) }
	#[inline(always)] fn yx(self) -> (B, A) { let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn yy(self) -> (B, B) { let s = self.s(); (s.1, s.1) }
	#[inline(always)] fn yz(self) -> (B, C) { let s = self.s(); (s.1, s.2) }
	#[inline(always)] fn yw(self) -> (B, D) { let s = self.s(); (s.1, s.3) }
	#[inline(always)] fn zx(self) -> (C, A) { let s = self.s(); (s.2, s.0) }
	#[inline(always)] fn zy(self) -> (C, B) { let s = self.s(); (s.2, s.1) }
	#[inline(always)] fn zz(self) -> (C, C) { let s = self.s(); (s.2, s.2) }
	#[inline(always)] fn zw(self) -> (C, D) { let s = self.s(); (s.2, s.3) }
	#[inline(always)] fn wx(self) -> (D, A) { let s = self.s(); (s.3, s.0) }
	#[inline(always)] fn wy(self) -> (D, B) { let s = self.s(); (s.3, s.1) }
	#[inline(always)] fn wz(self) -> (D, C) { let s = self.s(); (s.3, s.2) }
	#[inline(always)] fn ww(self) -> (D, D) { let s = self.s(); (s.3, s.3) }
	#[inline(always)] fn xxx(self) -> (A, A, A) { let s = self.s(); (s.0, s.0, s.0) }
	#[inline(always)] fn xxy(self) -> (A, A, B) { let s = self.s(); (s.0, s.0, s.1) }
	#[inline(always)] fn xxz(self) -> (A, A, C) { let s = self.s(); (s.0, s.0, s.2) }
	#[inline(always)] fn xxw(self) -> (A, A, D) { let s = self.s(); (s.0, s.0, s.3) }
	#[inline(always)] fn xyx(self) -> (A, B, A) { let s = self.s(); (s.0, s.1, s.0) }
	#[inline(always)] fn xyy(self) -> (A, B, B) { let s = self.s(); (s.0, s.1, s.1) }
	#[inline(always)] fn xyz(self) -> (A, B, C) { let s = self.s(); (s.0, s.1, s.2) }
	#[inline(always)] fn xyw(self) -> (A, B, D) { let s = self.s(); (s.0, s.1, s.3) }
	#[inline(always)] fn xzx(self) -> (A, C, A) { let s = self.s(); (s.0, s.2, s.0) }
	#[inline(always)] fn xzy(self) -> (A, C, B) { let s = self.s(); (s.0, s.2, s.1) }
	#[inline(always)] fn xzz(self) -> (A, C, C) { let s = self.s(); (s.0, s.2, s.2) }
	#[inline(always)] fn xzw(self) -> (A, C, D) { let s = self.s(); (s.0, s.2, s.3) }
	#[inline(always)] fn xwx(self) -> (A, D, A) { let s = self.s(); (s.0, s.3, s.0) }
	#[inline(always)] fn xwy(self) -> (A, D, B) { let s = self.s(); (s.0, s.3, s.1) }
	#[inline(always)] fn xwz(self) -> (A, D, C) { let s = self.s(); (s.0, s.3, s.2) }
	#[inline(always)] fn xww(self) -> (A, D, D) { let s = self.s(); (s.0, s.3, s.3) }
	#[inline(always)] fn yxx(self) -> (B, A, A) { let s = self.s(); (s.1, s.0, s.0) }
	#[inline(always)] fn yxy(self) -> (B, A, B) { let s = self.s(); (s.1, s.0, s.1) }
	#[inline(always)] fn yxz(self) -> (B, A, C) { let s = self.s(); (s.1, s.0, s.2) }
	#[inline(always)] fn yxw(self) -> (B, A, D) { let s = self.s(); (s.1, s.0, s.3) }
	#[inline(always)] fn yyx(self) -> (B, B, A) { let s = self.s(); (s.1, s.1, s.0) }
	#[inline(always)] fn yyy(self) -> (B, B, B) { let s = self.s(); (s.1, s.1, s.1) }
	#[inline(always)] fn yyz(self) -> (B, B, C) { let s = self.s(); (s.1, s.1, s.2) }
	#[inline(always)] fn yyw(self) -> (B, B, D) { let s = self.s(); (s.1, s.1, s.3) }
	#[inline(always)] fn yzx(self) -> (B, C, A) { let s = self.s(); (s.1, s.2, s.0) }
	#[inline(always)] fn yzy(self) -> (B, C, B) { let s = self.s(); (s.1, s.2, s.1) }
	#[inline(always)] fn yzz(self) -> (B, C, C) { let s = self.s(); (s.1, s.2, s.2) }
	#[inline(always)] fn yzw(self) -> (B, C, D) { let s = self.s(); (s.1, s.2, s.3) }
	#[inline(always)] fn ywx(self) -> (B, D, A) { let s = self.s(); (s.1, s.3, s.0) }
	#[inline(always)] fn ywy(self) -> (B, D, B) { let s = self.s(); (s.1, s.3, s.1) }
	#[inline(always)] fn ywz(self) -> (B, D, C) { let s = self.s(); (s.1, s.3, s.2) }
	#[inline(always)] fn yww(self) -> (B, D, D) { let s = self.s(); (s.1, s.3, s.3) }
	#[inline(always)] fn zxx(self) -> (C, A, A) { let s = self.s(); (s.2, s.0, s.0) }
	#[inline(always)] fn zxy(self) -> (C, A, B) { let s = self.s(); (s.2, s.0, s.1) }
	#[inline(always)] fn zxz(self) -> (C, A, C) { let s = self.s(); (s.2, s.0, s.2) }
	#[inline(always)] fn zxw(self) -> (C, A, D) { let s = self.s(); (s.2, s.0, s.3) }
	#[inline(always)] fn zyx(self) -> (C, B, A) { let s = self.s(); (s.2, s.1, s.0) }
	#[inline(always)] fn zyy(self) -> (C, B, B) { let s = self.s(); (s.2, s.1, s.1) }
	#[inline(always)] fn zyz(self) -> (C, B, C) { let s = self.s(); (s.2, s.1, s.2) }
	#[inline(always)] fn zyw(self) -> (C, B, D) { let s = self.s(); (s.2, s.1, s.3) }
	#[inline(always)] fn zzx(self) -> (C, C, A) { let s = self.s(); (s.2, s.2, s.0) }
	#[inline(always)] fn zzy(self) -> (C, C, B) { let s = self.s(); (s.2, s.2, s.1) }
	#[inline(always)] fn zzz(self) -> (C, C, C) { let s = self.s(); (s.2, s.2, s.2) }
	#[inline(always)] fn zzw(self) -> (C, C, D) { let s = self.s(); (s.2, s.2, s.3) }
	#[inline(always)] fn zwx(self) -> (C, D, A) { let s = self.s(); (s.2, s.3, s.0) }
	#[inline(always)] fn zwy(self) -> (C, D, B) { let s = self.s(); (s.2, s.3, s.1) }
	#[inline(always)] fn zwz(self) -> (C, D, C) { let s = self.s(); (s.2, s.3, s.2) }
	#[inline(always)] fn zww(self) -> (C, D, D) { let s = self.s(); (s.2, s.3, s.3) }
	#[inline(always)] fn wxx(self) -> (D, A, A) { let s = self.s(); (s.3, s.0, s.0) }
	#[inline(always)] fn wxy(self) -> (D, A, B) { let s = self.s(); (s.3, s.0, s.1) }
	#[inline(always)] fn wxz(self) -> (D, A, C) { let s = self.s(); (s.3, s.0, s.2) }
	#[inline(always)] fn wxw(self) -> (D, A, D) { let s = self.s(); (s.3, s.0, s.3) }
	#[inline(always)] fn wyx(self) -> (D, B, A) { let s = self.s(); (s.3, s.1, s.0) }
	#[inline(always)] fn wyy(self) -> (D, B, B) { let s = self.s(); (s.3, s.1, s.1) }
	#[inline(always)] fn wyz(self) -> (D, B, C) { let s = self.s(); (s.3, s.1, s.2) }
	#[inline(always)] fn wyw(self) -> (D, B, D) { let s = self.s(); (s.3, s.1, s.3) }
	#[inline(always)] fn wzx(self) -> (D, C, A) { let s = self.s(); (s.3, s.2, s.0) }
	#[inline(always)] fn wzy(self) -> (D, C, B) { let s = self.s(); (s.3, s.2, s.1) }
	#[inline(always)] fn wzz(self) -> (D, C, C) { let s = self.s(); (s.3, s.2, s.2) }
	#[inline(always)] fn wzw(self) -> (D, C, D) { let s = self.s(); (s.3, s.2, s.3) }
	#[inline(always)] fn wwx(self) -> (D, D, A) { let s = self.s(); (s.3, s.3, s.0) }
	#[inline(always)] fn wwy(self) -> (D, D, B) { let s = self.s(); (s.3, s.3, s.1) }
	#[inline(always)] fn wwz(self) -> (D, D, C) { let s = self.s(); (s.3, s.3, s.2) }
	#[inline(always)] fn www(self) -> (D, D, D) { let s = self.s(); (s.3, s.3, s.3) }

	#[inline(always)] fn xxxx(self) -> (A, A, A, A) { let s = self.s(); (s.0, s.0, s.0, s.0) }
	#[inline(always)] fn xxxy(self) -> (A, A, A, B) { let s = self.s(); (s.0, s.0, s.0, s.1) }
	#[inline(always)] fn xxxz(self) -> (A, A, A, C) { let s = self.s(); (s.0, s.0, s.0, s.2) }
	#[inline(always)] fn xxxw(self) -> (A, A, A, D) { let s = self.s(); (s.0, s.0, s.0, s.3) }
	#[inline(always)] fn xxyx(self) -> (A, A, B, A) { let s = self.s(); (s.0, s.0, s.1, s.0) }
	#[inline(always)] fn xxyy(self) -> (A, A, B, B) { let s = self.s(); (s.0, s.0, s.1, s.1) }
	#[inline(always)] fn xxyz(self) -> (A, A, B, C) { let s = self.s(); (s.0, s.0, s.1, s.2) }
	#[inline(always)] fn xxyw(self) -> (A, A, B, D) { let s = self.s(); (s.0, s.0, s.1, s.3) }
	#[inline(always)] fn xxzx(self) -> (A, A, C, A) { let s = self.s(); (s.0, s.0, s.2, s.0) }
	#[inline(always)] fn xxzy(self) -> (A, A, C, B) { let s = self.s(); (s.0, s.0, s.2, s.1) }
	#[inline(always)] fn xxzz(self) -> (A, A, C, C) { let s = self.s(); (s.0, s.0, s.2, s.2) }
	#[inline(always)] fn xxzw(self) -> (A, A, C, D) { let s = self.s(); (s.0, s.0, s.2, s.3) }
	#[inline(always)] fn xxwx(self) -> (A, A, D, A) { let s = self.s(); (s.0, s.0, s.3, s.0) }
	#[inline(always)] fn xxwy(self) -> (A, A, D, B) { let s = self.s(); (s.0, s.0, s.3, s.1) }
	#[inline(always)] fn xxwz(self) -> (A, A, D, C) { let s = self.s(); (s.0, s.0, s.3, s.2) }
	#[inline(always)] fn xxww(self) -> (A, A, D, D) { let s = self.s(); (s.0, s.0, s.3, s.3) }
	#[inline(always)] fn xyxx(self) -> (A, B, A, A) { let s = self.s(); (s.0, s.1, s.0, s.0) }
	#[inline(always)] fn xyxy(self) -> (A, B, A, B) { let s = self.s(); (s.0, s.1, s.0, s.1) }
	#[inline(always)] fn xyxz(self) -> (A, B, A, C) { let s = self.s(); (s.0, s.1, s.0, s.2) }
	#[inline(always)] fn xyxw(self) -> (A, B, A, D) { let s = self.s(); (s.0, s.1, s.0, s.3) }
	#[inline(always)] fn xyyx(self) -> (A, B, B, A) { let s = self.s(); (s.0, s.1, s.1, s.0) }
	#[inline(always)] fn xyyy(self) -> (A, B, B, B) { let s = self.s(); (s.0, s.1, s.1, s.1) }
	#[inline(always)] fn xyyz(self) -> (A, B, B, C) { let s = self.s(); (s.0, s.1, s.1, s.2) }
	#[inline(always)] fn xyyw(self) -> (A, B, B, D) { let s = self.s(); (s.0, s.1, s.1, s.3) }
	#[inline(always)] fn xyzx(self) -> (A, B, C, A) { let s = self.s(); (s.0, s.1, s.2, s.0) }
	#[inline(always)] fn xyzy(self) -> (A, B, C, B) { let s = self.s(); (s.0, s.1, s.2, s.1) }
	#[inline(always)] fn xyzz(self) -> (A, B, C, C) { let s = self.s(); (s.0, s.1, s.2, s.2) }
	#[inline(always)] fn xyzw(self) -> (A, B, C, D) { let s = self.s(); (s.0, s.1, s.2, s.3) }
	#[inline(always)] fn xywx(self) -> (A, B, D, A) { let s = self.s(); (s.0, s.1, s.3, s.0) }
	#[inline(always)] fn xywy(self) -> (A, B, D, B) { let s = self.s(); (s.0, s.1, s.3, s.1) }
	#[inline(always)] fn xywz(self) -> (A, B, D, C) { let s = self.s(); (s.0, s.1, s.3, s.2) }
	#[inline(always)] fn xyww(self) -> (A, B, D, D) { let s = self.s(); (s.0, s.1, s.3, s.3) }
	#[inline(always)] fn xzxx(self) -> (A, C, A, A) { let s = self.s(); (s.0, s.2, s.0, s.0) }
	#[inline(always)] fn xzxy(self) -> (A, C, A, B) { let s = self.s(); (s.0, s.2, s.0, s.1) }
	#[inline(always)] fn xzxz(self) -> (A, C, A, C) { let s = self.s(); (s.0, s.2, s.0, s.2) }
	#[inline(always)] fn xzxw(self) -> (A, C, A, D) { let s = self.s(); (s.0, s.2, s.0, s.3) }
	#[inline(always)] fn xzyx(self) -> (A, C, B, A) { let s = self.s(); (s.0, s.2, s.1, s.0) }
	#[inline(always)] fn xzyy(self) -> (A, C, B, B) { let s = self.s(); (s.0, s.2, s.1, s.1) }
	#[inline(always)] fn xzyz(self) -> (A, C, B, C) { let s = self.s(); (s.0, s.2, s.1, s.2) }
	#[inline(always)] fn xzyw(self) -> (A, C, B, D) { let s = self.s(); (s.0, s.2, s.1, s.3) }
	#[inline(always)] fn xzzx(self) -> (A, C, C, A) { let s = self.s(); (s.0, s.2, s.2, s.0) }
	#[inline(always)] fn xzzy(self) -> (A, C, C, B) { let s = self.s(); (s.0, s.2, s.2, s.1) }
	#[inline(always)] fn xzzz(self) -> (A, C, C, C) { let s = self.s(); (s.0, s.2, s.2, s.2) }
	#[inline(always)] fn xzzw(self) -> (A, C, C, D) { let s = self.s(); (s.0, s.2, s.2, s.3) }
	#[inline(always)] fn xzwx(self) -> (A, C, D, A) { let s = self.s(); (s.0, s.2, s.3, s.0) }
	#[inline(always)] fn xzwy(self) -> (A, C, D, B) { let s = self.s(); (s.0, s.2, s.3, s.1) }
	#[inline(always)] fn xzwz(self) -> (A, C, D, C) { let s = self.s(); (s.0, s.2, s.3, s.2) }
	#[inline(always)] fn xzww(self) -> (A, C, D, D) { let s = self.s(); (s.0, s.2, s.3, s.3) }
	#[inline(always)] fn xwxx(self) -> (A, D, A, A) { let s = self.s(); (s.0, s.3, s.0, s.0) }
	#[inline(always)] fn xwxy(self) -> (A, D, A, B) { let s = self.s(); (s.0, s.3, s.0, s.1) }
	#[inline(always)] fn xwxz(self) -> (A, D, A, C) { let s = self.s(); (s.0, s.3, s.0, s.2) }
	#[inline(always)] fn xwxw(self) -> (A, D, A, D) { let s = self.s(); (s.0, s.3, s.0, s.3) }
	#[inline(always)] fn xwyx(self) -> (A, D, B, A) { let s = self.s(); (s.0, s.3, s.1, s.0) }
	#[inline(always)] fn xwyy(self) -> (A, D, B, B) { let s = self.s(); (s.0, s.3, s.1, s.1) }
	#[inline(always)] fn xwyz(self) -> (A, D, B, C) { let s = self.s(); (s.0, s.3, s.1, s.2) }
	#[inline(always)] fn xwyw(self) -> (A, D, B, D) { let s = self.s(); (s.0, s.3, s.1, s.3) }
	#[inline(always)] fn xwzx(self) -> (A, D, C, A) { let s = self.s(); (s.0, s.3, s.2, s.0) }
	#[inline(always)] fn xwzy(self) -> (A, D, C, B) { let s = self.s(); (s.0, s.3, s.2, s.1) }
	#[inline(always)] fn xwzz(self) -> (A, D, C, C) { let s = self.s(); (s.0, s.3, s.2, s.2) }
	#[inline(always)] fn xwzw(self) -> (A, D, C, D) { let s = self.s(); (s.0, s.3, s.2, s.3) }
	#[inline(always)] fn xwwx(self) -> (A, D, D, A) { let s = self.s(); (s.0, s.3, s.3, s.0) }
	#[inline(always)] fn xwwy(self) -> (A, D, D, B) { let s = self.s(); (s.0, s.3, s.3, s.1) }
	#[inline(always)] fn xwwz(self) -> (A, D, D, C) { let s = self.s(); (s.0, s.3, s.3, s.2) }
	#[inline(always)] fn xwww(self) -> (A, D, D, D) { let s = self.s(); (s.0, s.3, s.3, s.3) }

	#[inline(always)] fn yxxx(self) -> (B, A, A, A) { let s = self.s(); (s.1, s.0, s.0, s.0) }
	#[inline(always)] fn yxxy(self) -> (B, A, A, B) { let s = self.s(); (s.1, s.0, s.0, s.1) }
	#[inline(always)] fn yxxz(self) -> (B, A, A, C) { let s = self.s(); (s.1, s.0, s.0, s.2) }
	#[inline(always)] fn yxxw(self) -> (B, A, A, D) { let s = self.s(); (s.1, s.0, s.0, s.3) }
	#[inline(always)] fn yxyx(self) -> (B, A, B, A) { let s = self.s(); (s.1, s.0, s.1, s.0) }
	#[inline(always)] fn yxyy(self) -> (B, A, B, B) { let s = self.s(); (s.1, s.0, s.1, s.1) }
	#[inline(always)] fn yxyz(self) -> (B, A, B, C) { let s = self.s(); (s.1, s.0, s.1, s.2) }
	#[inline(always)] fn yxyw(self) -> (B, A, B, D) { let s = self.s(); (s.1, s.0, s.1, s.3) }
	#[inline(always)] fn yxzx(self) -> (B, A, C, A) { let s = self.s(); (s.1, s.0, s.2, s.0) }
	#[inline(always)] fn yxzy(self) -> (B, A, C, B) { let s = self.s(); (s.1, s.0, s.2, s.1) }
	#[inline(always)] fn yxzz(self) -> (B, A, C, C) { let s = self.s(); (s.1, s.0, s.2, s.2) }
	#[inline(always)] fn yxzw(self) -> (B, A, C, D) { let s = self.s(); (s.1, s.0, s.2, s.3) }
	#[inline(always)] fn yxwx(self) -> (B, A, D, A) { let s = self.s(); (s.1, s.0, s.3, s.0) }
	#[inline(always)] fn yxwy(self) -> (B, A, D, B) { let s = self.s(); (s.1, s.0, s.3, s.1) }
	#[inline(always)] fn yxwz(self) -> (B, A, D, C) { let s = self.s(); (s.1, s.0, s.3, s.2) }
	#[inline(always)] fn yxww(self) -> (B, A, D, D) { let s = self.s(); (s.1, s.0, s.3, s.3) }
	#[inline(always)] fn yyxx(self) -> (B, B, A, A) { let s = self.s(); (s.1, s.1, s.0, s.0) }
	#[inline(always)] fn yyxy(self) -> (B, B, A, B) { let s = self.s(); (s.1, s.1, s.0, s.1) }
	#[inline(always)] fn yyxz(self) -> (B, B, A, C) { let s = self.s(); (s.1, s.1, s.0, s.2) }
	#[inline(always)] fn yyxw(self) -> (B, B, A, D) { let s = self.s(); (s.1, s.1, s.0, s.3) }
	#[inline(always)] fn yyyx(self) -> (B, B, B, A) { let s = self.s(); (s.1, s.1, s.1, s.0) }
	#[inline(always)] fn yyyy(self) -> (B, B, B, B) { let s = self.s(); (s.1, s.1, s.1, s.1) }
	#[inline(always)] fn yyyz(self) -> (B, B, B, C) { let s = self.s(); (s.1, s.1, s.1, s.2) }
	#[inline(always)] fn yyyw(self) -> (B, B, B, D) { let s = self.s(); (s.1, s.1, s.1, s.3) }
	#[inline(always)] fn yyzx(self) -> (B, B, C, A) { let s = self.s(); (s.1, s.1, s.2, s.0) }
	#[inline(always)] fn yyzy(self) -> (B, B, C, B) { let s = self.s(); (s.1, s.1, s.2, s.1) }
	#[inline(always)] fn yyzz(self) -> (B, B, C, C) { let s = self.s(); (s.1, s.1, s.2, s.2) }
	#[inline(always)] fn yyzw(self) -> (B, B, C, D) { let s = self.s(); (s.1, s.1, s.2, s.3) }
	#[inline(always)] fn yywx(self) -> (B, B, D, A) { let s = self.s(); (s.1, s.1, s.3, s.0) }
	#[inline(always)] fn yywy(self) -> (B, B, D, B) { let s = self.s(); (s.1, s.1, s.3, s.1) }
	#[inline(always)] fn yywz(self) -> (B, B, D, C) { let s = self.s(); (s.1, s.1, s.3, s.2) }
	#[inline(always)] fn yyww(self) -> (B, B, D, D) { let s = self.s(); (s.1, s.1, s.3, s.3) }
	#[inline(always)] fn yzxx(self) -> (B, C, A, A) { let s = self.s(); (s.1, s.2, s.0, s.0) }
	#[inline(always)] fn yzxy(self) -> (B, C, A, B) { let s = self.s(); (s.1, s.2, s.0, s.1) }
	#[inline(always)] fn yzxz(self) -> (B, C, A, C) { let s = self.s(); (s.1, s.2, s.0, s.2) }
	#[inline(always)] fn yzxw(self) -> (B, C, A, D) { let s = self.s(); (s.1, s.2, s.0, s.3) }
	#[inline(always)] fn yzyx(self) -> (B, C, B, A) { let s = self.s(); (s.1, s.2, s.1, s.0) }
	#[inline(always)] fn yzyy(self) -> (B, C, B, B) { let s = self.s(); (s.1, s.2, s.1, s.1) }
	#[inline(always)] fn yzyz(self) -> (B, C, B, C) { let s = self.s(); (s.1, s.2, s.1, s.2) }
	#[inline(always)] fn yzyw(self) -> (B, C, B, D) { let s = self.s(); (s.1, s.2, s.1, s.3) }
	#[inline(always)] fn yzzx(self) -> (B, C, C, A) { let s = self.s(); (s.1, s.2, s.2, s.0) }
	#[inline(always)] fn yzzy(self) -> (B, C, C, B) { let s = self.s(); (s.1, s.2, s.2, s.1) }
	#[inline(always)] fn yzzz(self) -> (B, C, C, C) { let s = self.s(); (s.1, s.2, s.2, s.2) }
	#[inline(always)] fn yzzw(self) -> (B, C, C, D) { let s = self.s(); (s.1, s.2, s.2, s.3) }
	#[inline(always)] fn yzwx(self) -> (B, C, D, A) { let s = self.s(); (s.1, s.2, s.3, s.0) }
	#[inline(always)] fn yzwy(self) -> (B, C, D, B) { let s = self.s(); (s.1, s.2, s.3, s.1) }
	#[inline(always)] fn yzwz(self) -> (B, C, D, C) { let s = self.s(); (s.1, s.2, s.3, s.2) }
	#[inline(always)] fn yzww(self) -> (B, C, D, D) { let s = self.s(); (s.1, s.2, s.3, s.3) }
	#[inline(always)] fn ywxx(self) -> (B, D, A, A) { let s = self.s(); (s.1, s.3, s.0, s.0) }
	#[inline(always)] fn ywxy(self) -> (B, D, A, B) { let s = self.s(); (s.1, s.3, s.0, s.1) }
	#[inline(always)] fn ywxz(self) -> (B, D, A, C) { let s = self.s(); (s.1, s.3, s.0, s.2) }
	#[inline(always)] fn ywxw(self) -> (B, D, A, D) { let s = self.s(); (s.1, s.3, s.0, s.3) }
	#[inline(always)] fn ywyx(self) -> (B, D, B, A) { let s = self.s(); (s.1, s.3, s.1, s.0) }
	#[inline(always)] fn ywyy(self) -> (B, D, B, B) { let s = self.s(); (s.1, s.3, s.1, s.1) }
	#[inline(always)] fn ywyz(self) -> (B, D, B, C) { let s = self.s(); (s.1, s.3, s.1, s.2) }
	#[inline(always)] fn ywyw(self) -> (B, D, B, D) { let s = self.s(); (s.1, s.3, s.1, s.3) }
	#[inline(always)] fn ywzx(self) -> (B, D, C, A) { let s = self.s(); (s.1, s.3, s.2, s.0) }
	#[inline(always)] fn ywzy(self) -> (B, D, C, B) { let s = self.s(); (s.1, s.3, s.2, s.1) }
	#[inline(always)] fn ywzz(self) -> (B, D, C, C) { let s = self.s(); (s.1, s.3, s.2, s.2) }
	#[inline(always)] fn ywzw(self) -> (B, D, C, D) { let s = self.s(); (s.1, s.3, s.2, s.3) }
	#[inline(always)] fn ywwx(self) -> (B, D, D, A) { let s = self.s(); (s.1, s.3, s.3, s.0) }
	#[inline(always)] fn ywwy(self) -> (B, D, D, B) { let s = self.s(); (s.1, s.3, s.3, s.1) }
	#[inline(always)] fn ywwz(self) -> (B, D, D, C) { let s = self.s(); (s.1, s.3, s.3, s.2) }
	#[inline(always)] fn ywww(self) -> (B, D, D, D) { let s = self.s(); (s.1, s.3, s.3, s.3) }

	#[inline(always)] fn zxxx(self) -> (C, A, A, A) { let s = self.s(); (s.2, s.0, s.0, s.0) }
	#[inline(always)] fn zxxy(self) -> (C, A, A, B) { let s = self.s(); (s.2, s.0, s.0, s.1) }
	#[inline(always)] fn zxxz(self) -> (C, A, A, C) { let s = self.s(); (s.2, s.0, s.0, s.2) }
	#[inline(always)] fn zxxw(self) -> (C, A, A, D) { let s = self.s(); (s.2, s.0, s.0, s.3) }
	#[inline(always)] fn zxyx(self) -> (C, A, B, A) { let s = self.s(); (s.2, s.0, s.1, s.0) }
	#[inline(always)] fn zxyy(self) -> (C, A, B, B) { let s = self.s(); (s.2, s.0, s.1, s.1) }
	#[inline(always)] fn zxyz(self) -> (C, A, B, C) { let s = self.s(); (s.2, s.0, s.1, s.2) }
	#[inline(always)] fn zxyw(self) -> (C, A, B, D) { let s = self.s(); (s.2, s.0, s.1, s.3) }
	#[inline(always)] fn zxzx(self) -> (C, A, C, A) { let s = self.s(); (s.2, s.0, s.2, s.0) }
	#[inline(always)] fn zxzy(self) -> (C, A, C, B) { let s = self.s(); (s.2, s.0, s.2, s.1) }
	#[inline(always)] fn zxzz(self) -> (C, A, C, C) { let s = self.s(); (s.2, s.0, s.2, s.2) }
	#[inline(always)] fn zxzw(self) -> (C, A, C, D) { let s = self.s(); (s.2, s.0, s.2, s.3) }
	#[inline(always)] fn zxwx(self) -> (C, A, D, A) { let s = self.s(); (s.2, s.0, s.3, s.0) }
	#[inline(always)] fn zxwy(self) -> (C, A, D, B) { let s = self.s(); (s.2, s.0, s.3, s.1) }
	#[inline(always)] fn zxwz(self) -> (C, A, D, C) { let s = self.s(); (s.2, s.0, s.3, s.2) }
	#[inline(always)] fn zxww(self) -> (C, A, D, D) { let s = self.s(); (s.2, s.0, s.3, s.3) }
	#[inline(always)] fn zyxx(self) -> (C, B, A, A) { let s = self.s(); (s.2, s.1, s.0, s.0) }
	#[inline(always)] fn zyxy(self) -> (C, B, A, B) { let s = self.s(); (s.2, s.1, s.0, s.1) }
	#[inline(always)] fn zyxz(self) -> (C, B, A, C) { let s = self.s(); (s.2, s.1, s.0, s.2) }
	#[inline(always)] fn zyxw(self) -> (C, B, A, D) { let s = self.s(); (s.2, s.1, s.0, s.3) }
	#[inline(always)] fn zyyx(self) -> (C, B, B, A) { let s = self.s(); (s.2, s.1, s.1, s.0) }
	#[inline(always)] fn zyyy(self) -> (C, B, B, B) { let s = self.s(); (s.2, s.1, s.1, s.1) }
	#[inline(always)] fn zyyz(self) -> (C, B, B, C) { let s = self.s(); (s.2, s.1, s.1, s.2) }
	#[inline(always)] fn zyyw(self) -> (C, B, B, D) { let s = self.s(); (s.2, s.1, s.1, s.3) }
	#[inline(always)] fn zyzx(self) -> (C, B, C, A) { let s = self.s(); (s.2, s.1, s.2, s.0) }
	#[inline(always)] fn zyzy(self) -> (C, B, C, B) { let s = self.s(); (s.2, s.1, s.2, s.1) }
	#[inline(always)] fn zyzz(self) -> (C, B, C, C) { let s = self.s(); (s.2, s.1, s.2, s.2) }
	#[inline(always)] fn zyzw(self) -> (C, B, C, D) { let s = self.s(); (s.2, s.1, s.2, s.3) }
	#[inline(always)] fn zywx(self) -> (C, B, D, A) { let s = self.s(); (s.2, s.1, s.3, s.0) }
	#[inline(always)] fn zywy(self) -> (C, B, D, B) { let s = self.s(); (s.2, s.1, s.3, s.1) }
	#[inline(always)] fn zywz(self) -> (C, B, D, C) { let s = self.s(); (s.2, s.1, s.3, s.2) }
	#[inline(always)] fn zyww(self) -> (C, B, D, D) { let s = self.s(); (s.2, s.1, s.3, s.3) }
	#[inline(always)] fn zzxx(self) -> (C, C, A, A) { let s = self.s(); (s.2, s.2, s.0, s.0) }
	#[inline(always)] fn zzxy(self) -> (C, C, A, B) { let s = self.s(); (s.2, s.2, s.0, s.1) }
	#[inline(always)] fn zzxz(self) -> (C, C, A, C) { let s = self.s(); (s.2, s.2, s.0, s.2) }
	#[inline(always)] fn zzxw(self) -> (C, C, A, D) { let s = self.s(); (s.2, s.2, s.0, s.3) }
	#[inline(always)] fn zzyx(self) -> (C, C, B, A) { let s = self.s(); (s.2, s.2, s.1, s.0) }
	#[inline(always)] fn zzyy(self) -> (C, C, B, B) { let s = self.s(); (s.2, s.2, s.1, s.1) }
	#[inline(always)] fn zzyz(self) -> (C, C, B, C) { let s = self.s(); (s.2, s.2, s.1, s.2) }
	#[inline(always)] fn zzyw(self) -> (C, C, B, D) { let s = self.s(); (s.2, s.2, s.1, s.3) }
	#[inline(always)] fn zzzx(self) -> (C, C, C, A) { let s = self.s(); (s.2, s.2, s.2, s.0) }
	#[inline(always)] fn zzzy(self) -> (C, C, C, B) { let s = self.s(); (s.2, s.2, s.2, s.1) }
	#[inline(always)] fn zzzz(self) -> (C, C, C, C) { let s = self.s(); (s.2, s.2, s.2, s.2) }
	#[inline(always)] fn zzzw(self) -> (C, C, C, D) { let s = self.s(); (s.2, s.2, s.2, s.3) }
	#[inline(always)] fn zzwx(self) -> (C, C, D, A) { let s = self.s(); (s.2, s.2, s.3, s.0) }
	#[inline(always)] fn zzwy(self) -> (C, C, D, B) { let s = self.s(); (s.2, s.2, s.3, s.1) }
	#[inline(always)] fn zzwz(self) -> (C, C, D, C) { let s = self.s(); (s.2, s.2, s.3, s.2) }
	#[inline(always)] fn zzww(self) -> (C, C, D, D) { let s = self.s(); (s.2, s.2, s.3, s.3) }
	#[inline(always)] fn zwxx(self) -> (C, D, A, A) { let s = self.s(); (s.2, s.3, s.0, s.0) }
	#[inline(always)] fn zwxy(self) -> (C, D, A, B) { let s = self.s(); (s.2, s.3, s.0, s.1) }
	#[inline(always)] fn zwxz(self) -> (C, D, A, C) { let s = self.s(); (s.2, s.3, s.0, s.2) }
	#[inline(always)] fn zwxw(self) -> (C, D, A, D) { let s = self.s(); (s.2, s.3, s.0, s.3) }
	#[inline(always)] fn zwyx(self) -> (C, D, B, A) { let s = self.s(); (s.2, s.3, s.1, s.0) }
	#[inline(always)] fn zwyy(self) -> (C, D, B, B) { let s = self.s(); (s.2, s.3, s.1, s.1) }
	#[inline(always)] fn zwyz(self) -> (C, D, B, C) { let s = self.s(); (s.2, s.3, s.1, s.2) }
	#[inline(always)] fn zwyw(self) -> (C, D, B, D) { let s = self.s(); (s.2, s.3, s.1, s.3) }
	#[inline(always)] fn zwzx(self) -> (C, D, C, A) { let s = self.s(); (s.2, s.3, s.2, s.0) }
	#[inline(always)] fn zwzy(self) -> (C, D, C, B) { let s = self.s(); (s.2, s.3, s.2, s.1) }
	#[inline(always)] fn zwzz(self) -> (C, D, C, C) { let s = self.s(); (s.2, s.3, s.2, s.2) }
	#[inline(always)] fn zwzw(self) -> (C, D, C, D) { let s = self.s(); (s.2, s.3, s.2, s.3) }
	#[inline(always)] fn zwwx(self) -> (C, D, D, A) { let s = self.s(); (s.2, s.3, s.3, s.0) }
	#[inline(always)] fn zwwy(self) -> (C, D, D, B) { let s = self.s(); (s.2, s.3, s.3, s.1) }
	#[inline(always)] fn zwwz(self) -> (C, D, D, C) { let s = self.s(); (s.2, s.3, s.3, s.2) }
	#[inline(always)] fn zwww(self) -> (C, D, D, D) { let s = self.s(); (s.2, s.3, s.3, s.3) }

	#[inline(always)] fn wxxx(self) -> (D, A, A, A) { let s = self.s(); (s.3, s.0, s.0, s.0) }
	#[inline(always)] fn wxxy(self) -> (D, A, A, B) { let s = self.s(); (s.3, s.0, s.0, s.1) }
	#[inline(always)] fn wxxz(self) -> (D, A, A, C) { let s = self.s(); (s.3, s.0, s.0, s.2) }
	#[inline(always)] fn wxxw(self) -> (D, A, A, D) { let s = self.s(); (s.3, s.0, s.0, s.3) }
	#[inline(always)] fn wxyx(self) -> (D, A, B, A) { let s = self.s(); (s.3, s.0, s.1, s.0) }
	#[inline(always)] fn wxyy(self) -> (D, A, B, B) { let s = self.s(); (s.3, s.0, s.1, s.1) }
	#[inline(always)] fn wxyz(self) -> (D, A, B, C) { let s = self.s(); (s.3, s.0, s.1, s.2) }
	#[inline(always)] fn wxyw(self) -> (D, A, B, D) { let s = self.s(); (s.3, s.0, s.1, s.3) }
	#[inline(always)] fn wxzx(self) -> (D, A, C, A) { let s = self.s(); (s.3, s.0, s.2, s.0) }
	#[inline(always)] fn wxzy(self) -> (D, A, C, B) { let s = self.s(); (s.3, s.0, s.2, s.1) }
	#[inline(always)] fn wxzz(self) -> (D, A, C, C) { let s = self.s(); (s.3, s.0, s.2, s.2) }
	#[inline(always)] fn wxzw(self) -> (D, A, C, D) { let s = self.s(); (s.3, s.0, s.2, s.3) }
	#[inline(always)] fn wxwx(self) -> (D, A, D, A) { let s = self.s(); (s.3, s.0, s.3, s.0) }
	#[inline(always)] fn wxwy(self) -> (D, A, D, B) { let s = self.s(); (s.3, s.0, s.3, s.1) }
	#[inline(always)] fn wxwz(self) -> (D, A, D, C) { let s = self.s(); (s.3, s.0, s.3, s.2) }
	#[inline(always)] fn wxww(self) -> (D, A, D, D) { let s = self.s(); (s.3, s.0, s.3, s.3) }
	#[inline(always)] fn wyxx(self) -> (D, B, A, A) { let s = self.s(); (s.3, s.1, s.0, s.0) }
	#[inline(always)] fn wyxy(self) -> (D, B, A, B) { let s = self.s(); (s.3, s.1, s.0, s.1) }
	#[inline(always)] fn wyxz(self) -> (D, B, A, C) { let s = self.s(); (s.3, s.1, s.0, s.2) }
	#[inline(always)] fn wyxw(self) -> (D, B, A, D) { let s = self.s(); (s.3, s.1, s.0, s.3) }
	#[inline(always)] fn wyyx(self) -> (D, B, B, A) { let s = self.s(); (s.3, s.1, s.1, s.0) }
	#[inline(always)] fn wyyy(self) -> (D, B, B, B) { let s = self.s(); (s.3, s.1, s.1, s.1) }
	#[inline(always)] fn wyyz(self) -> (D, B, B, C) { let s = self.s(); (s.3, s.1, s.1, s.2) }
	#[inline(always)] fn wyyw(self) -> (D, B, B, D) { let s = self.s(); (s.3, s.1, s.1, s.3) }
	#[inline(always)] fn wyzx(self) -> (D, B, C, A) { let s = self.s(); (s.3, s.1, s.2, s.0) }
	#[inline(always)] fn wyzy(self) -> (D, B, C, B) { let s = self.s(); (s.3, s.1, s.2, s.1) }
	#[inline(always)] fn wyzz(self) -> (D, B, C, C) { let s = self.s(); (s.3, s.1, s.2, s.2) }
	#[inline(always)] fn wyzw(self) -> (D, B, C, D) { let s = self.s(); (s.3, s.1, s.2, s.3) }
	#[inline(always)] fn wywx(self) -> (D, B, D, A) { let s = self.s(); (s.3, s.1, s.3, s.0) }
	#[inline(always)] fn wywy(self) -> (D, B, D, B) { let s = self.s(); (s.3, s.1, s.3, s.1) }
	#[inline(always)] fn wywz(self) -> (D, B, D, C) { let s = self.s(); (s.3, s.1, s.3, s.2) }
	#[inline(always)] fn wyww(self) -> (D, B, D, D) { let s = self.s(); (s.3, s.1, s.3, s.3) }
	#[inline(always)] fn wzxx(self) -> (D, C, A, A) { let s = self.s(); (s.3, s.2, s.0, s.0) }
	#[inline(always)] fn wzxy(self) -> (D, C, A, B) { let s = self.s(); (s.3, s.2, s.0, s.1) }
	#[inline(always)] fn wzxz(self) -> (D, C, A, C) { let s = self.s(); (s.3, s.2, s.0, s.2) }
	#[inline(always)] fn wzxw(self) -> (D, C, A, D) { let s = self.s(); (s.3, s.2, s.0, s.3) }
	#[inline(always)] fn wzyx(self) -> (D, C, B, A) { let s = self.s(); (s.3, s.2, s.1, s.0) }
	#[inline(always)] fn wzyy(self) -> (D, C, B, B) { let s = self.s(); (s.3, s.2, s.1, s.1) }
	#[inline(always)] fn wzyz(self) -> (D, C, B, C) { let s = self.s(); (s.3, s.2, s.1, s.2) }
	#[inline(always)] fn wzyw(self) -> (D, C, B, D) { let s = self.s(); (s.3, s.2, s.1, s.3) }
	#[inline(always)] fn wzzx(self) -> (D, C, C, A) { let s = self.s(); (s.3, s.2, s.2, s.0) }
	#[inline(always)] fn wzzy(self) -> (D, C, C, B) { let s = self.s(); (s.3, s.2, s.2, s.1) }
	#[inline(always)] fn wzzz(self) -> (D, C, C, C) { let s = self.s(); (s.3, s.2, s.2, s.2) }
	#[inline(always)] fn wzzw(self) -> (D, C, C, D) { let s = self.s(); (s.3, s.2, s.2, s.3) }
	#[inline(always)] fn wzwx(self) -> (D, C, D, A) { let s = self.s(); (s.3, s.2, s.3, s.0) }
	#[inline(always)] fn wzwy(self) -> (D, C, D, B) { let s = self.s(); (s.3, s.2, s.3, s.1) }
	#[inline(always)] fn wzwz(self) -> (D, C, D, C) { let s = self.s(); (s.3, s.2, s.3, s.2) }
	#[inline(always)] fn wzww(self) -> (D, C, D, D) { let s = self.s(); (s.3, s.2, s.3, s.3) }
	#[inline(always)] fn wwxx(self) -> (D, D, A, A) { let s = self.s(); (s.3, s.3, s.0, s.0) }
	#[inline(always)] fn wwxy(self) -> (D, D, A, B) { let s = self.s(); (s.3, s.3, s.0, s.1) }
	#[inline(always)] fn wwxz(self) -> (D, D, A, C) { let s = self.s(); (s.3, s.3, s.0, s.2) }
	#[inline(always)] fn wwxw(self) -> (D, D, A, D) { let s = self.s(); (s.3, s.3, s.0, s.3) }
	#[inline(always)] fn wwyx(self) -> (D, D, B, A) { let s = self.s(); (s.3, s.3, s.1, s.0) }
	#[inline(always)] fn wwyy(self) -> (D, D, B, B) { let s = self.s(); (s.3, s.3, s.1, s.1) }
	#[inline(always)] fn wwyz(self) -> (D, D, B, C) { let s = self.s(); (s.3, s.3, s.1, s.2) }
	#[inline(always)] fn wwyw(self) -> (D, D, B, D) { let s = self.s(); (s.3, s.3, s.1, s.3) }
	#[inline(always)] fn wwzx(self) -> (D, D, C, A) { let s = self.s(); (s.3, s.3, s.2, s.0) }
	#[inline(always)] fn wwzy(self) -> (D, D, C, B) { let s = self.s(); (s.3, s.3, s.2, s.1) }
	#[inline(always)] fn wwzz(self) -> (D, D, C, C) { let s = self.s(); (s.3, s.3, s.2, s.2) }
	#[inline(always)] fn wwzw(self) -> (D, D, C, D) { let s = self.s(); (s.3, s.3, s.2, s.3) }
	#[inline(always)] fn wwwx(self) -> (D, D, D, A) { let s = self.s(); (s.3, s.3, s.3, s.0) }
	#[inline(always)] fn wwwy(self) -> (D, D, D, B) { let s = self.s(); (s.3, s.3, s.3, s.1) }
	#[inline(always)] fn wwwz(self) -> (D, D, D, C) { let s = self.s(); (s.3, s.3, s.3, s.2) }
	#[inline(always)] fn wwww(self) -> (D, D, D, D) { let s = self.s(); (s.3, s.3, s.3, s.3) }

	#[inline(always)] fn r(self) -> A { self.s().0 }
	#[inline(always)] fn g(self) -> B { self.s().1 }
	#[inline(always)] fn b(self) -> C { self.s().2 }
	#[inline(always)] fn a(self) -> D { self.s().3 }
	#[inline(always)] fn rr(self) -> (A, A) { let s = self.s(); (s.0, s.0) }
	#[inline(always)] fn rg(self) -> (A, B) { let s = self.s(); (s.0, s.1) }
	#[inline(always)] fn rb(self) -> (A, C) { let s = self.s(); (s.0, s.2) }
	#[inline(always)] fn ra(self) -> (A, D) { let s = self.s(); (s.0, s.3) }
	#[inline(always)] fn gr(self) -> (B, A) { let s = self.s(); (s.1, s.0) }
	#[inline(always)] fn gg(self) -> (B, B) { let s = self.s(); (s.1, s.1) }
	#[inline(always)] fn gb(self) -> (B, C) { let s = self.s(); (s.1, s.2) }
	#[inline(always)] fn ga(self) -> (B, D) { let s = self.s(); (s.1, s.3) }
	#[inline(always)] fn br(self) -> (C, A) { let s = self.s(); (s.2, s.0) }
	#[inline(always)] fn bg(self) -> (C, B) { let s = self.s(); (s.2, s.1) }
	#[inline(always)] fn bb(self) -> (C, C) { let s = self.s(); (s.2, s.2) }
	#[inline(always)] fn ba(self) -> (C, D) { let s = self.s(); (s.2, s.3) }
	#[inline(always)] fn ar(self) -> (D, A) { let s = self.s(); (s.3, s.0) }
	#[inline(always)] fn ag(self) -> (D, B) { let s = self.s(); (s.3, s.1) }
	#[inline(always)] fn ab(self) -> (D, C) { let s = self.s(); (s.3, s.2) }
	#[inline(always)] fn aa(self) -> (D, D) { let s = self.s(); (s.3, s.3) }
	#[inline(always)] fn rrr(self) -> (A, A, A) { let s = self.s(); (s.0, s.0, s.0) }
	#[inline(always)] fn rrg(self) -> (A, A, B) { let s = self.s(); (s.0, s.0, s.1) }
	#[inline(always)] fn rrb(self) -> (A, A, C) { let s = self.s(); (s.0, s.0, s.2) }
	#[inline(always)] fn rra(self) -> (A, A, D) { let s = self.s(); (s.0, s.0, s.3) }
	#[inline(always)] fn rgr(self) -> (A, B, A) { let s = self.s(); (s.0, s.1, s.0) }
	#[inline(always)] fn rgg(self) -> (A, B, B) { let s = self.s(); (s.0, s.1, s.1) }
	#[inline(always)] fn rgb(self) -> (A, B, C) { let s = self.s(); (s.0, s.1, s.2) }
	#[inline(always)] fn rga(self) -> (A, B, D) { let s = self.s(); (s.0, s.1, s.3) }
	#[inline(always)] fn rbr(self) -> (A, C, A) { let s = self.s(); (s.0, s.2, s.0) }
	#[inline(always)] fn rbg(self) -> (A, C, B) { let s = self.s(); (s.0, s.2, s.1) }
	#[inline(always)] fn rbb(self) -> (A, C, C) { let s = self.s(); (s.0, s.2, s.2) }
	#[inline(always)] fn rba(self) -> (A, C, D) { let s = self.s(); (s.0, s.2, s.3) }
	#[inline(always)] fn rar(self) -> (A, D, A) { let s = self.s(); (s.0, s.3, s.0) }
	#[inline(always)] fn rag(self) -> (A, D, B) { let s = self.s(); (s.0, s.3, s.1) }
	#[inline(always)] fn rab(self) -> (A, D, C) { let s = self.s(); (s.0, s.3, s.2) }
	#[inline(always)] fn raa(self) -> (A, D, D) { let s = self.s(); (s.0, s.3, s.3) }
	#[inline(always)] fn grr(self) -> (B, A, A) { let s = self.s(); (s.1, s.0, s.0) }
	#[inline(always)] fn grg(self) -> (B, A, B) { let s = self.s(); (s.1, s.0, s.1) }
	#[inline(always)] fn grb(self) -> (B, A, C) { let s = self.s(); (s.1, s.0, s.2) }
	#[inline(always)] fn gra(self) -> (B, A, D) { let s = self.s(); (s.1, s.0, s.3) }
	#[inline(always)] fn ggr(self) -> (B, B, A) { let s = self.s(); (s.1, s.1, s.0) }
	#[inline(always)] fn ggg(self) -> (B, B, B) { let s = self.s(); (s.1, s.1, s.1) }
	#[inline(always)] fn ggb(self) -> (B, B, C) { let s = self.s(); (s.1, s.1, s.2) }
	#[inline(always)] fn gga(self) -> (B, B, D) { let s = self.s(); (s.1, s.1, s.3) }
	#[inline(always)] fn gbr(self) -> (B, C, A) { let s = self.s(); (s.1, s.2, s.0) }
	#[inline(always)] fn gbg(self) -> (B, C, B) { let s = self.s(); (s.1, s.2, s.1) }
	#[inline(always)] fn gbb(self) -> (B, C, C) { let s = self.s(); (s.1, s.2, s.2) }
	#[inline(always)] fn gba(self) -> (B, C, D) { let s = self.s(); (s.1, s.2, s.3) }
	#[inline(always)] fn gar(self) -> (B, D, A) { let s = self.s(); (s.1, s.3, s.0) }
	#[inline(always)] fn gag(self) -> (B, D, B) { let s = self.s(); (s.1, s.3, s.1) }
	#[inline(always)] fn gab(self) -> (B, D, C) { let s = self.s(); (s.1, s.3, s.2) }
	#[inline(always)] fn gaa(self) -> (B, D, D) { let s = self.s(); (s.1, s.3, s.3) }
	#[inline(always)] fn brr(self) -> (C, A, A) { let s = self.s(); (s.2, s.0, s.0) }
	#[inline(always)] fn brg(self) -> (C, A, B) { let s = self.s(); (s.2, s.0, s.1) }
	#[inline(always)] fn brb(self) -> (C, A, C) { let s = self.s(); (s.2, s.0, s.2) }
	#[inline(always)] fn bra(self) -> (C, A, D) { let s = self.s(); (s.2, s.0, s.3) }
	#[inline(always)] fn bgr(self) -> (C, B, A) { let s = self.s(); (s.2, s.1, s.0) }
	#[inline(always)] fn bgg(self) -> (C, B, B) { let s = self.s(); (s.2, s.1, s.1) }
	#[inline(always)] fn bgb(self) -> (C, B, C) { let s = self.s(); (s.2, s.1, s.2) }
	#[inline(always)] fn bga(self) -> (C, B, D) { let s = self.s(); (s.2, s.1, s.3) }
	#[inline(always)] fn bbr(self) -> (C, C, A) { let s = self.s(); (s.2, s.2, s.0) }
	#[inline(always)] fn bbg(self) -> (C, C, B) { let s = self.s(); (s.2, s.2, s.1) }
	#[inline(always)] fn bbb(self) -> (C, C, C) { let s = self.s(); (s.2, s.2, s.2) }
	#[inline(always)] fn bba(self) -> (C, C, D) { let s = self.s(); (s.2, s.2, s.3) }
	#[inline(always)] fn bar(self) -> (C, D, A) { let s = self.s(); (s.2, s.3, s.0) }
	#[inline(always)] fn bag(self) -> (C, D, B) { let s = self.s(); (s.2, s.3, s.1) }
	#[inline(always)] fn bab(self) -> (C, D, C) { let s = self.s(); (s.2, s.3, s.2) }
	#[inline(always)] fn baa(self) -> (C, D, D) { let s = self.s(); (s.2, s.3, s.3) }
	#[inline(always)] fn arr(self) -> (D, A, A) { let s = self.s(); (s.3, s.0, s.0) }
	#[inline(always)] fn arg(self) -> (D, A, B) { let s = self.s(); (s.3, s.0, s.1) }
	#[inline(always)] fn arb(self) -> (D, A, C) { let s = self.s(); (s.3, s.0, s.2) }
	#[inline(always)] fn ara(self) -> (D, A, D) { let s = self.s(); (s.3, s.0, s.3) }
	#[inline(always)] fn agr(self) -> (D, B, A) { let s = self.s(); (s.3, s.1, s.0) }
	#[inline(always)] fn agg(self) -> (D, B, B) { let s = self.s(); (s.3, s.1, s.1) }
	#[inline(always)] fn agb(self) -> (D, B, C) { let s = self.s(); (s.3, s.1, s.2) }
	#[inline(always)] fn aga(self) -> (D, B, D) { let s = self.s(); (s.3, s.1, s.3) }
	#[inline(always)] fn abr(self) -> (D, C, A) { let s = self.s(); (s.3, s.2, s.0) }
	#[inline(always)] fn abg(self) -> (D, C, B) { let s = self.s(); (s.3, s.2, s.1) }
	#[inline(always)] fn abb(self) -> (D, C, C) { let s = self.s(); (s.3, s.2, s.2) }
	#[inline(always)] fn aba(self) -> (D, C, D) { let s = self.s(); (s.3, s.2, s.3) }
	#[inline(always)] fn aar(self) -> (D, D, A) { let s = self.s(); (s.3, s.3, s.0) }
	#[inline(always)] fn aag(self) -> (D, D, B) { let s = self.s(); (s.3, s.3, s.1) }
	#[inline(always)] fn aab(self) -> (D, D, C) { let s = self.s(); (s.3, s.3, s.2) }
	#[inline(always)] fn aaa(self) -> (D, D, D) { let s = self.s(); (s.3, s.3, s.3) }

	#[inline(always)] fn rrrr(self) -> (A, A, A, A) { let s = self.s(); (s.0, s.0, s.0, s.0) }
	#[inline(always)] fn rrrg(self) -> (A, A, A, B) { let s = self.s(); (s.0, s.0, s.0, s.1) }
	#[inline(always)] fn rrrb(self) -> (A, A, A, C) { let s = self.s(); (s.0, s.0, s.0, s.2) }
	#[inline(always)] fn rrra(self) -> (A, A, A, D) { let s = self.s(); (s.0, s.0, s.0, s.3) }
	#[inline(always)] fn rrgr(self) -> (A, A, B, A) { let s = self.s(); (s.0, s.0, s.1, s.0) }
	#[inline(always)] fn rrgg(self) -> (A, A, B, B) { let s = self.s(); (s.0, s.0, s.1, s.1) }
	#[inline(always)] fn rrgb(self) -> (A, A, B, C) { let s = self.s(); (s.0, s.0, s.1, s.2) }
	#[inline(always)] fn rrga(self) -> (A, A, B, D) { let s = self.s(); (s.0, s.0, s.1, s.3) }
	#[inline(always)] fn rrbr(self) -> (A, A, C, A) { let s = self.s(); (s.0, s.0, s.2, s.0) }
	#[inline(always)] fn rrbg(self) -> (A, A, C, B) { let s = self.s(); (s.0, s.0, s.2, s.1) }
	#[inline(always)] fn rrbb(self) -> (A, A, C, C) { let s = self.s(); (s.0, s.0, s.2, s.2) }
	#[inline(always)] fn rrba(self) -> (A, A, C, D) { let s = self.s(); (s.0, s.0, s.2, s.3) }
	#[inline(always)] fn rrar(self) -> (A, A, D, A) { let s = self.s(); (s.0, s.0, s.3, s.0) }
	#[inline(always)] fn rrag(self) -> (A, A, D, B) { let s = self.s(); (s.0, s.0, s.3, s.1) }
	#[inline(always)] fn rrab(self) -> (A, A, D, C) { let s = self.s(); (s.0, s.0, s.3, s.2) }
	#[inline(always)] fn rraa(self) -> (A, A, D, D) { let s = self.s(); (s.0, s.0, s.3, s.3) }
	#[inline(always)] fn rgrr(self) -> (A, B, A, A) { let s = self.s(); (s.0, s.1, s.0, s.0) }
	#[inline(always)] fn rgrg(self) -> (A, B, A, B) { let s = self.s(); (s.0, s.1, s.0, s.1) }
	#[inline(always)] fn rgrb(self) -> (A, B, A, C) { let s = self.s(); (s.0, s.1, s.0, s.2) }
	#[inline(always)] fn rgra(self) -> (A, B, A, D) { let s = self.s(); (s.0, s.1, s.0, s.3) }
	#[inline(always)] fn rggr(self) -> (A, B, B, A) { let s = self.s(); (s.0, s.1, s.1, s.0) }
	#[inline(always)] fn rggg(self) -> (A, B, B, B) { let s = self.s(); (s.0, s.1, s.1, s.1) }
	#[inline(always)] fn rggb(self) -> (A, B, B, C) { let s = self.s(); (s.0, s.1, s.1, s.2) }
	#[inline(always)] fn rgga(self) -> (A, B, B, D) { let s = self.s(); (s.0, s.1, s.1, s.3) }
	#[inline(always)] fn rgbr(self) -> (A, B, C, A) { let s = self.s(); (s.0, s.1, s.2, s.0) }
	#[inline(always)] fn rgbg(self) -> (A, B, C, B) { let s = self.s(); (s.0, s.1, s.2, s.1) }
	#[inline(always)] fn rgbb(self) -> (A, B, C, C) { let s = self.s(); (s.0, s.1, s.2, s.2) }
	#[inline(always)] fn rgba(self) -> (A, B, C, D) { let s = self.s(); (s.0, s.1, s.2, s.3) }
	#[inline(always)] fn rgar(self) -> (A, B, D, A) { let s = self.s(); (s.0, s.1, s.3, s.0) }
	#[inline(always)] fn rgag(self) -> (A, B, D, B) { let s = self.s(); (s.0, s.1, s.3, s.1) }
	#[inline(always)] fn rgab(self) -> (A, B, D, C) { let s = self.s(); (s.0, s.1, s.3, s.2) }
	#[inline(always)] fn rgaa(self) -> (A, B, D, D) { let s = self.s(); (s.0, s.1, s.3, s.3) }
	#[inline(always)] fn rbrr(self) -> (A, C, A, A) { let s = self.s(); (s.0, s.2, s.0, s.0) }
	#[inline(always)] fn rbrg(self) -> (A, C, A, B) { let s = self.s(); (s.0, s.2, s.0, s.1) }
	#[inline(always)] fn rbrb(self) -> (A, C, A, C) { let s = self.s(); (s.0, s.2, s.0, s.2) }
	#[inline(always)] fn rbra(self) -> (A, C, A, D) { let s = self.s(); (s.0, s.2, s.0, s.3) }
	#[inline(always)] fn rbgr(self) -> (A, C, B, A) { let s = self.s(); (s.0, s.2, s.1, s.0) }
	#[inline(always)] fn rbgg(self) -> (A, C, B, B) { let s = self.s(); (s.0, s.2, s.1, s.1) }
	#[inline(always)] fn rbgb(self) -> (A, C, B, C) { let s = self.s(); (s.0, s.2, s.1, s.2) }
	#[inline(always)] fn rbga(self) -> (A, C, B, D) { let s = self.s(); (s.0, s.2, s.1, s.3) }
	#[inline(always)] fn rbbr(self) -> (A, C, C, A) { let s = self.s(); (s.0, s.2, s.2, s.0) }
	#[inline(always)] fn rbbg(self) -> (A, C, C, B) { let s = self.s(); (s.0, s.2, s.2, s.1) }
	#[inline(always)] fn rbbb(self) -> (A, C, C, C) { let s = self.s(); (s.0, s.2, s.2, s.2) }
	#[inline(always)] fn rbba(self) -> (A, C, C, D) { let s = self.s(); (s.0, s.2, s.2, s.3) }
	#[inline(always)] fn rbar(self) -> (A, C, D, A) { let s = self.s(); (s.0, s.2, s.3, s.0) }
	#[inline(always)] fn rbag(self) -> (A, C, D, B) { let s = self.s(); (s.0, s.2, s.3, s.1) }
	#[inline(always)] fn rbab(self) -> (A, C, D, C) { let s = self.s(); (s.0, s.2, s.3, s.2) }
	#[inline(always)] fn rbaa(self) -> (A, C, D, D) { let s = self.s(); (s.0, s.2, s.3, s.3) }
	#[inline(always)] fn rarr(self) -> (A, D, A, A) { let s = self.s(); (s.0, s.3, s.0, s.0) }
	#[inline(always)] fn rarg(self) -> (A, D, A, B) { let s = self.s(); (s.0, s.3, s.0, s.1) }
	#[inline(always)] fn rarb(self) -> (A, D, A, C) { let s = self.s(); (s.0, s.3, s.0, s.2) }
	#[inline(always)] fn rara(self) -> (A, D, A, D) { let s = self.s(); (s.0, s.3, s.0, s.3) }
	#[inline(always)] fn ragr(self) -> (A, D, B, A) { let s = self.s(); (s.0, s.3, s.1, s.0) }
	#[inline(always)] fn ragg(self) -> (A, D, B, B) { let s = self.s(); (s.0, s.3, s.1, s.1) }
	#[inline(always)] fn ragb(self) -> (A, D, B, C) { let s = self.s(); (s.0, s.3, s.1, s.2) }
	#[inline(always)] fn raga(self) -> (A, D, B, D) { let s = self.s(); (s.0, s.3, s.1, s.3) }
	#[inline(always)] fn rabr(self) -> (A, D, C, A) { let s = self.s(); (s.0, s.3, s.2, s.0) }
	#[inline(always)] fn rabg(self) -> (A, D, C, B) { let s = self.s(); (s.0, s.3, s.2, s.1) }
	#[inline(always)] fn rabb(self) -> (A, D, C, C) { let s = self.s(); (s.0, s.3, s.2, s.2) }
	#[inline(always)] fn raba(self) -> (A, D, C, D) { let s = self.s(); (s.0, s.3, s.2, s.3) }
	#[inline(always)] fn raar(self) -> (A, D, D, A) { let s = self.s(); (s.0, s.3, s.3, s.0) }
	#[inline(always)] fn raag(self) -> (A, D, D, B) { let s = self.s(); (s.0, s.3, s.3, s.1) }
	#[inline(always)] fn raab(self) -> (A, D, D, C) { let s = self.s(); (s.0, s.3, s.3, s.2) }
	#[inline(always)] fn raaa(self) -> (A, D, D, D) { let s = self.s(); (s.0, s.3, s.3, s.3) }

	#[inline(always)] fn grrr(self) -> (B, A, A, A) { let s = self.s(); (s.1, s.0, s.0, s.0) }
	#[inline(always)] fn grrg(self) -> (B, A, A, B) { let s = self.s(); (s.1, s.0, s.0, s.1) }
	#[inline(always)] fn grrb(self) -> (B, A, A, C) { let s = self.s(); (s.1, s.0, s.0, s.2) }
	#[inline(always)] fn grra(self) -> (B, A, A, D) { let s = self.s(); (s.1, s.0, s.0, s.3) }
	#[inline(always)] fn grgr(self) -> (B, A, B, A) { let s = self.s(); (s.1, s.0, s.1, s.0) }
	#[inline(always)] fn grgg(self) -> (B, A, B, B) { let s = self.s(); (s.1, s.0, s.1, s.1) }
	#[inline(always)] fn grgb(self) -> (B, A, B, C) { let s = self.s(); (s.1, s.0, s.1, s.2) }
	#[inline(always)] fn grga(self) -> (B, A, B, D) { let s = self.s(); (s.1, s.0, s.1, s.3) }
	#[inline(always)] fn grbr(self) -> (B, A, C, A) { let s = self.s(); (s.1, s.0, s.2, s.0) }
	#[inline(always)] fn grbg(self) -> (B, A, C, B) { let s = self.s(); (s.1, s.0, s.2, s.1) }
	#[inline(always)] fn grbb(self) -> (B, A, C, C) { let s = self.s(); (s.1, s.0, s.2, s.2) }
	#[inline(always)] fn grba(self) -> (B, A, C, D) { let s = self.s(); (s.1, s.0, s.2, s.3) }
	#[inline(always)] fn grar(self) -> (B, A, D, A) { let s = self.s(); (s.1, s.0, s.3, s.0) }
	#[inline(always)] fn grag(self) -> (B, A, D, B) { let s = self.s(); (s.1, s.0, s.3, s.1) }
	#[inline(always)] fn grab(self) -> (B, A, D, C) { let s = self.s(); (s.1, s.0, s.3, s.2) }
	#[inline(always)] fn graa(self) -> (B, A, D, D) { let s = self.s(); (s.1, s.0, s.3, s.3) }
	#[inline(always)] fn ggrr(self) -> (B, B, A, A) { let s = self.s(); (s.1, s.1, s.0, s.0) }
	#[inline(always)] fn ggrg(self) -> (B, B, A, B) { let s = self.s(); (s.1, s.1, s.0, s.1) }
	#[inline(always)] fn ggrb(self) -> (B, B, A, C) { let s = self.s(); (s.1, s.1, s.0, s.2) }
	#[inline(always)] fn ggra(self) -> (B, B, A, D) { let s = self.s(); (s.1, s.1, s.0, s.3) }
	#[inline(always)] fn gggr(self) -> (B, B, B, A) { let s = self.s(); (s.1, s.1, s.1, s.0) }
	#[inline(always)] fn gggg(self) -> (B, B, B, B) { let s = self.s(); (s.1, s.1, s.1, s.1) }
	#[inline(always)] fn gggb(self) -> (B, B, B, C) { let s = self.s(); (s.1, s.1, s.1, s.2) }
	#[inline(always)] fn ggga(self) -> (B, B, B, D) { let s = self.s(); (s.1, s.1, s.1, s.3) }
	#[inline(always)] fn ggbr(self) -> (B, B, C, A) { let s = self.s(); (s.1, s.1, s.2, s.0) }
	#[inline(always)] fn ggbg(self) -> (B, B, C, B) { let s = self.s(); (s.1, s.1, s.2, s.1) }
	#[inline(always)] fn ggbb(self) -> (B, B, C, C) { let s = self.s(); (s.1, s.1, s.2, s.2) }
	#[inline(always)] fn ggba(self) -> (B, B, C, D) { let s = self.s(); (s.1, s.1, s.2, s.3) }
	#[inline(always)] fn ggar(self) -> (B, B, D, A) { let s = self.s(); (s.1, s.1, s.3, s.0) }
	#[inline(always)] fn ggag(self) -> (B, B, D, B) { let s = self.s(); (s.1, s.1, s.3, s.1) }
	#[inline(always)] fn ggab(self) -> (B, B, D, C) { let s = self.s(); (s.1, s.1, s.3, s.2) }
	#[inline(always)] fn ggaa(self) -> (B, B, D, D) { let s = self.s(); (s.1, s.1, s.3, s.3) }
	#[inline(always)] fn gbrr(self) -> (B, C, A, A) { let s = self.s(); (s.1, s.2, s.0, s.0) }
	#[inline(always)] fn gbrg(self) -> (B, C, A, B) { let s = self.s(); (s.1, s.2, s.0, s.1) }
	#[inline(always)] fn gbrb(self) -> (B, C, A, C) { let s = self.s(); (s.1, s.2, s.0, s.2) }
	#[inline(always)] fn gbra(self) -> (B, C, A, D) { let s = self.s(); (s.1, s.2, s.0, s.3) }
	#[inline(always)] fn gbgr(self) -> (B, C, B, A) { let s = self.s(); (s.1, s.2, s.1, s.0) }
	#[inline(always)] fn gbgg(self) -> (B, C, B, B) { let s = self.s(); (s.1, s.2, s.1, s.1) }
	#[inline(always)] fn gbgb(self) -> (B, C, B, C) { let s = self.s(); (s.1, s.2, s.1, s.2) }
	#[inline(always)] fn gbga(self) -> (B, C, B, D) { let s = self.s(); (s.1, s.2, s.1, s.3) }
	#[inline(always)] fn gbbr(self) -> (B, C, C, A) { let s = self.s(); (s.1, s.2, s.2, s.0) }
	#[inline(always)] fn gbbg(self) -> (B, C, C, B) { let s = self.s(); (s.1, s.2, s.2, s.1) }
	#[inline(always)] fn gbbb(self) -> (B, C, C, C) { let s = self.s(); (s.1, s.2, s.2, s.2) }
	#[inline(always)] fn gbba(self) -> (B, C, C, D) { let s = self.s(); (s.1, s.2, s.2, s.3) }
	#[inline(always)] fn gbar(self) -> (B, C, D, A) { let s = self.s(); (s.1, s.2, s.3, s.0) }
	#[inline(always)] fn gbag(self) -> (B, C, D, B) { let s = self.s(); (s.1, s.2, s.3, s.1) }
	#[inline(always)] fn gbab(self) -> (B, C, D, C) { let s = self.s(); (s.1, s.2, s.3, s.2) }
	#[inline(always)] fn gbaa(self) -> (B, C, D, D) { let s = self.s(); (s.1, s.2, s.3, s.3) }
	#[inline(always)] fn garr(self) -> (B, D, A, A) { let s = self.s(); (s.1, s.3, s.0, s.0) }
	#[inline(always)] fn garg(self) -> (B, D, A, B) { let s = self.s(); (s.1, s.3, s.0, s.1) }
	#[inline(always)] fn garb(self) -> (B, D, A, C) { let s = self.s(); (s.1, s.3, s.0, s.2) }
	#[inline(always)] fn gara(self) -> (B, D, A, D) { let s = self.s(); (s.1, s.3, s.0, s.3) }
	#[inline(always)] fn gagr(self) -> (B, D, B, A) { let s = self.s(); (s.1, s.3, s.1, s.0) }
	#[inline(always)] fn gagg(self) -> (B, D, B, B) { let s = self.s(); (s.1, s.3, s.1, s.1) }
	#[inline(always)] fn gagb(self) -> (B, D, B, C) { let s = self.s(); (s.1, s.3, s.1, s.2) }
	#[inline(always)] fn gaga(self) -> (B, D, B, D) { let s = self.s(); (s.1, s.3, s.1, s.3) }
	#[inline(always)] fn gabr(self) -> (B, D, C, A) { let s = self.s(); (s.1, s.3, s.2, s.0) }
	#[inline(always)] fn gabg(self) -> (B, D, C, B) { let s = self.s(); (s.1, s.3, s.2, s.1) }
	#[inline(always)] fn gabb(self) -> (B, D, C, C) { let s = self.s(); (s.1, s.3, s.2, s.2) }
	#[inline(always)] fn gaba(self) -> (B, D, C, D) { let s = self.s(); (s.1, s.3, s.2, s.3) }
	#[inline(always)] fn gaar(self) -> (B, D, D, A) { let s = self.s(); (s.1, s.3, s.3, s.0) }
	#[inline(always)] fn gaag(self) -> (B, D, D, B) { let s = self.s(); (s.1, s.3, s.3, s.1) }
	#[inline(always)] fn gaab(self) -> (B, D, D, C) { let s = self.s(); (s.1, s.3, s.3, s.2) }
	#[inline(always)] fn gaaa(self) -> (B, D, D, D) { let s = self.s(); (s.1, s.3, s.3, s.3) }

	#[inline(always)] fn brrr(self) -> (C, A, A, A) { let s = self.s(); (s.2, s.0, s.0, s.0) }
	#[inline(always)] fn brrg(self) -> (C, A, A, B) { let s = self.s(); (s.2, s.0, s.0, s.1) }
	#[inline(always)] fn brrb(self) -> (C, A, A, C) { let s = self.s(); (s.2, s.0, s.0, s.2) }
	#[inline(always)] fn brra(self) -> (C, A, A, D) { let s = self.s(); (s.2, s.0, s.0, s.3) }
	#[inline(always)] fn brgr(self) -> (C, A, B, A) { let s = self.s(); (s.2, s.0, s.1, s.0) }
	#[inline(always)] fn brgg(self) -> (C, A, B, B) { let s = self.s(); (s.2, s.0, s.1, s.1) }
	#[inline(always)] fn brgb(self) -> (C, A, B, C) { let s = self.s(); (s.2, s.0, s.1, s.2) }
	#[inline(always)] fn brga(self) -> (C, A, B, D) { let s = self.s(); (s.2, s.0, s.1, s.3) }
	#[inline(always)] fn brbr(self) -> (C, A, C, A) { let s = self.s(); (s.2, s.0, s.2, s.0) }
	#[inline(always)] fn brbg(self) -> (C, A, C, B) { let s = self.s(); (s.2, s.0, s.2, s.1) }
	#[inline(always)] fn brbb(self) -> (C, A, C, C) { let s = self.s(); (s.2, s.0, s.2, s.2) }
	#[inline(always)] fn brba(self) -> (C, A, C, D) { let s = self.s(); (s.2, s.0, s.2, s.3) }
	#[inline(always)] fn brar(self) -> (C, A, D, A) { let s = self.s(); (s.2, s.0, s.3, s.0) }
	#[inline(always)] fn brag(self) -> (C, A, D, B) { let s = self.s(); (s.2, s.0, s.3, s.1) }
	#[inline(always)] fn brab(self) -> (C, A, D, C) { let s = self.s(); (s.2, s.0, s.3, s.2) }
	#[inline(always)] fn braa(self) -> (C, A, D, D) { let s = self.s(); (s.2, s.0, s.3, s.3) }
	#[inline(always)] fn bgrr(self) -> (C, B, A, A) { let s = self.s(); (s.2, s.1, s.0, s.0) }
	#[inline(always)] fn bgrg(self) -> (C, B, A, B) { let s = self.s(); (s.2, s.1, s.0, s.1) }
	#[inline(always)] fn bgrb(self) -> (C, B, A, C) { let s = self.s(); (s.2, s.1, s.0, s.2) }
	#[inline(always)] fn bgra(self) -> (C, B, A, D) { let s = self.s(); (s.2, s.1, s.0, s.3) }
	#[inline(always)] fn bggr(self) -> (C, B, B, A) { let s = self.s(); (s.2, s.1, s.1, s.0) }
	#[inline(always)] fn bggg(self) -> (C, B, B, B) { let s = self.s(); (s.2, s.1, s.1, s.1) }
	#[inline(always)] fn bggb(self) -> (C, B, B, C) { let s = self.s(); (s.2, s.1, s.1, s.2) }
	#[inline(always)] fn bgga(self) -> (C, B, B, D) { let s = self.s(); (s.2, s.1, s.1, s.3) }
	#[inline(always)] fn bgbr(self) -> (C, B, C, A) { let s = self.s(); (s.2, s.1, s.2, s.0) }
	#[inline(always)] fn bgbg(self) -> (C, B, C, B) { let s = self.s(); (s.2, s.1, s.2, s.1) }
	#[inline(always)] fn bgbb(self) -> (C, B, C, C) { let s = self.s(); (s.2, s.1, s.2, s.2) }
	#[inline(always)] fn bgba(self) -> (C, B, C, D) { let s = self.s(); (s.2, s.1, s.2, s.3) }
	#[inline(always)] fn bgar(self) -> (C, B, D, A) { let s = self.s(); (s.2, s.1, s.3, s.0) }
	#[inline(always)] fn bgag(self) -> (C, B, D, B) { let s = self.s(); (s.2, s.1, s.3, s.1) }
	#[inline(always)] fn bgab(self) -> (C, B, D, C) { let s = self.s(); (s.2, s.1, s.3, s.2) }
	#[inline(always)] fn bgaa(self) -> (C, B, D, D) { let s = self.s(); (s.2, s.1, s.3, s.3) }
	#[inline(always)] fn bbrr(self) -> (C, C, A, A) { let s = self.s(); (s.2, s.2, s.0, s.0) }
	#[inline(always)] fn bbrg(self) -> (C, C, A, B) { let s = self.s(); (s.2, s.2, s.0, s.1) }
	#[inline(always)] fn bbrb(self) -> (C, C, A, C) { let s = self.s(); (s.2, s.2, s.0, s.2) }
	#[inline(always)] fn bbra(self) -> (C, C, A, D) { let s = self.s(); (s.2, s.2, s.0, s.3) }
	#[inline(always)] fn bbgr(self) -> (C, C, B, A) { let s = self.s(); (s.2, s.2, s.1, s.0) }
	#[inline(always)] fn bbgg(self) -> (C, C, B, B) { let s = self.s(); (s.2, s.2, s.1, s.1) }
	#[inline(always)] fn bbgb(self) -> (C, C, B, C) { let s = self.s(); (s.2, s.2, s.1, s.2) }
	#[inline(always)] fn bbga(self) -> (C, C, B, D) { let s = self.s(); (s.2, s.2, s.1, s.3) }
	#[inline(always)] fn bbbr(self) -> (C, C, C, A) { let s = self.s(); (s.2, s.2, s.2, s.0) }
	#[inline(always)] fn bbbg(self) -> (C, C, C, B) { let s = self.s(); (s.2, s.2, s.2, s.1) }
	#[inline(always)] fn bbbb(self) -> (C, C, C, C) { let s = self.s(); (s.2, s.2, s.2, s.2) }
	#[inline(always)] fn bbba(self) -> (C, C, C, D) { let s = self.s(); (s.2, s.2, s.2, s.3) }
	#[inline(always)] fn bbar(self) -> (C, C, D, A) { let s = self.s(); (s.2, s.2, s.3, s.0) }
	#[inline(always)] fn bbag(self) -> (C, C, D, B) { let s = self.s(); (s.2, s.2, s.3, s.1) }
	#[inline(always)] fn bbab(self) -> (C, C, D, C) { let s = self.s(); (s.2, s.2, s.3, s.2) }
	#[inline(always)] fn bbaa(self) -> (C, C, D, D) { let s = self.s(); (s.2, s.2, s.3, s.3) }
	#[inline(always)] fn barr(self) -> (C, D, A, A) { let s = self.s(); (s.2, s.3, s.0, s.0) }
	#[inline(always)] fn barg(self) -> (C, D, A, B) { let s = self.s(); (s.2, s.3, s.0, s.1) }
	#[inline(always)] fn barb(self) -> (C, D, A, C) { let s = self.s(); (s.2, s.3, s.0, s.2) }
	#[inline(always)] fn bara(self) -> (C, D, A, D) { let s = self.s(); (s.2, s.3, s.0, s.3) }
	#[inline(always)] fn bagr(self) -> (C, D, B, A) { let s = self.s(); (s.2, s.3, s.1, s.0) }
	#[inline(always)] fn bagg(self) -> (C, D, B, B) { let s = self.s(); (s.2, s.3, s.1, s.1) }
	#[inline(always)] fn bagb(self) -> (C, D, B, C) { let s = self.s(); (s.2, s.3, s.1, s.2) }
	#[inline(always)] fn baga(self) -> (C, D, B, D) { let s = self.s(); (s.2, s.3, s.1, s.3) }
	#[inline(always)] fn babr(self) -> (C, D, C, A) { let s = self.s(); (s.2, s.3, s.2, s.0) }
	#[inline(always)] fn babg(self) -> (C, D, C, B) { let s = self.s(); (s.2, s.3, s.2, s.1) }
	#[inline(always)] fn babb(self) -> (C, D, C, C) { let s = self.s(); (s.2, s.3, s.2, s.2) }
	#[inline(always)] fn baba(self) -> (C, D, C, D) { let s = self.s(); (s.2, s.3, s.2, s.3) }
	#[inline(always)] fn baar(self) -> (C, D, D, A) { let s = self.s(); (s.2, s.3, s.3, s.0) }
	#[inline(always)] fn baag(self) -> (C, D, D, B) { let s = self.s(); (s.2, s.3, s.3, s.1) }
	#[inline(always)] fn baab(self) -> (C, D, D, C) { let s = self.s(); (s.2, s.3, s.3, s.2) }
	#[inline(always)] fn baaa(self) -> (C, D, D, D) { let s = self.s(); (s.2, s.3, s.3, s.3) }

	#[inline(always)] fn arrr(self) -> (D, A, A, A) { let s = self.s(); (s.3, s.0, s.0, s.0) }
	#[inline(always)] fn arrg(self) -> (D, A, A, B) { let s = self.s(); (s.3, s.0, s.0, s.1) }
	#[inline(always)] fn arrb(self) -> (D, A, A, C) { let s = self.s(); (s.3, s.0, s.0, s.2) }
	#[inline(always)] fn arra(self) -> (D, A, A, D) { let s = self.s(); (s.3, s.0, s.0, s.3) }
	#[inline(always)] fn argr(self) -> (D, A, B, A) { let s = self.s(); (s.3, s.0, s.1, s.0) }
	#[inline(always)] fn argg(self) -> (D, A, B, B) { let s = self.s(); (s.3, s.0, s.1, s.1) }
	#[inline(always)] fn argb(self) -> (D, A, B, C) { let s = self.s(); (s.3, s.0, s.1, s.2) }
	#[inline(always)] fn arga(self) -> (D, A, B, D) { let s = self.s(); (s.3, s.0, s.1, s.3) }
	#[inline(always)] fn arbr(self) -> (D, A, C, A) { let s = self.s(); (s.3, s.0, s.2, s.0) }
	#[inline(always)] fn arbg(self) -> (D, A, C, B) { let s = self.s(); (s.3, s.0, s.2, s.1) }
	#[inline(always)] fn arbb(self) -> (D, A, C, C) { let s = self.s(); (s.3, s.0, s.2, s.2) }
	#[inline(always)] fn arba(self) -> (D, A, C, D) { let s = self.s(); (s.3, s.0, s.2, s.3) }
	#[inline(always)] fn arar(self) -> (D, A, D, A) { let s = self.s(); (s.3, s.0, s.3, s.0) }
	#[inline(always)] fn arag(self) -> (D, A, D, B) { let s = self.s(); (s.3, s.0, s.3, s.1) }
	#[inline(always)] fn arab(self) -> (D, A, D, C) { let s = self.s(); (s.3, s.0, s.3, s.2) }
	#[inline(always)] fn araa(self) -> (D, A, D, D) { let s = self.s(); (s.3, s.0, s.3, s.3) }
	#[inline(always)] fn agrr(self) -> (D, B, A, A) { let s = self.s(); (s.3, s.1, s.0, s.0) }
	#[inline(always)] fn agrg(self) -> (D, B, A, B) { let s = self.s(); (s.3, s.1, s.0, s.1) }
	#[inline(always)] fn agrb(self) -> (D, B, A, C) { let s = self.s(); (s.3, s.1, s.0, s.2) }
	#[inline(always)] fn agra(self) -> (D, B, A, D) { let s = self.s(); (s.3, s.1, s.0, s.3) }
	#[inline(always)] fn aggr(self) -> (D, B, B, A) { let s = self.s(); (s.3, s.1, s.1, s.0) }
	#[inline(always)] fn aggg(self) -> (D, B, B, B) { let s = self.s(); (s.3, s.1, s.1, s.1) }
	#[inline(always)] fn aggb(self) -> (D, B, B, C) { let s = self.s(); (s.3, s.1, s.1, s.2) }
	#[inline(always)] fn agga(self) -> (D, B, B, D) { let s = self.s(); (s.3, s.1, s.1, s.3) }
	#[inline(always)] fn agbr(self) -> (D, B, C, A) { let s = self.s(); (s.3, s.1, s.2, s.0) }
	#[inline(always)] fn agbg(self) -> (D, B, C, B) { let s = self.s(); (s.3, s.1, s.2, s.1) }
	#[inline(always)] fn agbb(self) -> (D, B, C, C) { let s = self.s(); (s.3, s.1, s.2, s.2) }
	#[inline(always)] fn agba(self) -> (D, B, C, D) { let s = self.s(); (s.3, s.1, s.2, s.3) }
	#[inline(always)] fn agar(self) -> (D, B, D, A) { let s = self.s(); (s.3, s.1, s.3, s.0) }
	#[inline(always)] fn agag(self) -> (D, B, D, B) { let s = self.s(); (s.3, s.1, s.3, s.1) }
	#[inline(always)] fn agab(self) -> (D, B, D, C) { let s = self.s(); (s.3, s.1, s.3, s.2) }
	#[inline(always)] fn agaa(self) -> (D, B, D, D) { let s = self.s(); (s.3, s.1, s.3, s.3) }
	#[inline(always)] fn abrr(self) -> (D, C, A, A) { let s = self.s(); (s.3, s.2, s.0, s.0) }
	#[inline(always)] fn abrg(self) -> (D, C, A, B) { let s = self.s(); (s.3, s.2, s.0, s.1) }
	#[inline(always)] fn abrb(self) -> (D, C, A, C) { let s = self.s(); (s.3, s.2, s.0, s.2) }
	#[inline(always)] fn abra(self) -> (D, C, A, D) { let s = self.s(); (s.3, s.2, s.0, s.3) }
	#[inline(always)] fn abgr(self) -> (D, C, B, A) { let s = self.s(); (s.3, s.2, s.1, s.0) }
	#[inline(always)] fn abgg(self) -> (D, C, B, B) { let s = self.s(); (s.3, s.2, s.1, s.1) }
	#[inline(always)] fn abgb(self) -> (D, C, B, C) { let s = self.s(); (s.3, s.2, s.1, s.2) }
	#[inline(always)] fn abga(self) -> (D, C, B, D) { let s = self.s(); (s.3, s.2, s.1, s.3) }
	#[inline(always)] fn abbr(self) -> (D, C, C, A) { let s = self.s(); (s.3, s.2, s.2, s.0) }
	#[inline(always)] fn abbg(self) -> (D, C, C, B) { let s = self.s(); (s.3, s.2, s.2, s.1) }
	#[inline(always)] fn abbb(self) -> (D, C, C, C) { let s = self.s(); (s.3, s.2, s.2, s.2) }
	#[inline(always)] fn abba(self) -> (D, C, C, D) { let s = self.s(); (s.3, s.2, s.2, s.3) }
	#[inline(always)] fn abar(self) -> (D, C, D, A) { let s = self.s(); (s.3, s.2, s.3, s.0) }
	#[inline(always)] fn abag(self) -> (D, C, D, B) { let s = self.s(); (s.3, s.2, s.3, s.1) }
	#[inline(always)] fn abab(self) -> (D, C, D, C) { let s = self.s(); (s.3, s.2, s.3, s.2) }
	#[inline(always)] fn abaa(self) -> (D, C, D, D) { let s = self.s(); (s.3, s.2, s.3, s.3) }
	#[inline(always)] fn aarr(self) -> (D, D, A, A) { let s = self.s(); (s.3, s.3, s.0, s.0) }
	#[inline(always)] fn aarg(self) -> (D, D, A, B) { let s = self.s(); (s.3, s.3, s.0, s.1) }
	#[inline(always)] fn aarb(self) -> (D, D, A, C) { let s = self.s(); (s.3, s.3, s.0, s.2) }
	#[inline(always)] fn aara(self) -> (D, D, A, D) { let s = self.s(); (s.3, s.3, s.0, s.3) }
	#[inline(always)] fn aagr(self) -> (D, D, B, A) { let s = self.s(); (s.3, s.3, s.1, s.0) }
	#[inline(always)] fn aagg(self) -> (D, D, B, B) { let s = self.s(); (s.3, s.3, s.1, s.1) }
	#[inline(always)] fn aagb(self) -> (D, D, B, C) { let s = self.s(); (s.3, s.3, s.1, s.2) }
	#[inline(always)] fn aaga(self) -> (D, D, B, D) { let s = self.s(); (s.3, s.3, s.1, s.3) }
	#[inline(always)] fn aabr(self) -> (D, D, C, A) { let s = self.s(); (s.3, s.3, s.2, s.0) }
	#[inline(always)] fn aabg(self) -> (D, D, C, B) { let s = self.s(); (s.3, s.3, s.2, s.1) }
	#[inline(always)] fn aabb(self) -> (D, D, C, C) { let s = self.s(); (s.3, s.3, s.2, s.2) }
	#[inline(always)] fn aaba(self) -> (D, D, C, D) { let s = self.s(); (s.3, s.3, s.2, s.3) }
	#[inline(always)] fn aaar(self) -> (D, D, D, A) { let s = self.s(); (s.3, s.3, s.3, s.0) }
	#[inline(always)] fn aaag(self) -> (D, D, D, B) { let s = self.s(); (s.3, s.3, s.3, s.1) }
	#[inline(always)] fn aaab(self) -> (D, D, D, C) { let s = self.s(); (s.3, s.3, s.3, s.2) }
	#[inline(always)] fn aaaa(self) -> (D, D, D, D) { let s = self.s(); (s.3, s.3, s.3, s.3) }
}
}
use s::*;

impl<A: Copy, B: Copy> TupleSwizzle2<A, B> for (A, B) {
	#[inline(always)]
	fn s(self) -> (A, B) {
		self
	}
}
impl<T: Copy> TupleSwizzle2<T, T> for [T; 2] {
	#[inline(always)]
	fn s(self) -> (T, T) {
		(self[0], self[1])
	}
}

impl<A: Copy, B: Copy, C: Copy> TupleSwizzle3<A, B, C> for (A, B, C) {
	#[inline(always)]
	fn s(self) -> (A, B, C) {
		self
	}
}
impl<T: Copy> TupleSwizzle3<T, T, T> for [T; 3] {
	#[inline(always)]
	fn s(self) -> (T, T, T) {
		(self[0], self[1], self[2])
	}
}

impl<A: Copy, B: Copy, C: Copy, D: Copy> TupleSwizzle4<A, B, C, D> for (A, B, C, D) {
	#[inline(always)]
	fn s(self) -> (A, B, C, D) {
		self
	}
}
impl<T: Copy> TupleSwizzle4<T, T, T, T> for [T; 4] {
	#[inline(always)]
	fn s(self) -> (T, T, T, T) {
		(self[0], self[1], self[2], self[3])
	}
}
